# -*- coding: utf-8 -*-
# vim: ft=yaml
---
driver:
  name: linode
  flavor: 2048

provisioner:
  name: salt_solo
  is_file_root: true
  salt_copy_filter:
    - .kitchen
    - .git
  state_top:
    base:
      "*":
        - test.mockup
        - elasticsearch
  pillars:
    top.sls:
      base:
        "*":
          - elasticsearch

platforms:
  - name: debian_jessie

suites:
  - name: default
    provisioner:
      pillars:
        elasticsearch.sls:
          elasticsearch:
            enabled: true

  - name: custom
    provisioner:
      pillars-from-files:
        elasticsearch.sls: pillar_custom.sls
